title: My Jekyll Blog
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my blog!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://username.github.io" # the base hostname & protocol for your site
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
